# Generated by Django 5.1.4 on 2025-01-12 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumption',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.technology'),
            preserve_default=False,
        ),
    ]
