# Generated by Django 5.1.4 on 2025-01-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_aboutmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmessages',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
