# Generated by Django 5.1.4 on 2025-01-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_technology_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.country'),
            preserve_default=False,
        ),
    ]
