# Generated by Django 5.1.4 on 2025-01-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_project_location_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_customization',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
