# Generated by Django 5.1.4 on 2025-01-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_project_additional_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='customization_form',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
