# Generated by Django 5.1.4 on 2025-01-05 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_location_name'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyImplemented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.country')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologies.technology')),
            ],
        ),
    ]
